/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthTodosImport } from './routes/_auth.todos'
import { Route as AuthListsImport } from './routes/_auth.lists'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthTodosRoute = AuthTodosImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AuthRoute,
} as any)

const AuthListsRoute = AuthListsImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/lists': {
      id: '/_auth/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof AuthListsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/todos': {
      id: '/_auth/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AuthTodosImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthListsRoute: typeof AuthListsRoute
  AuthTodosRoute: typeof AuthTodosRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthListsRoute: AuthListsRoute,
  AuthTodosRoute: AuthTodosRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/lists': typeof AuthListsRoute
  '/todos': typeof AuthTodosRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/lists': typeof AuthListsRoute
  '/todos': typeof AuthTodosRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/lists': typeof AuthListsRoute
  '/_auth/todos': typeof AuthTodosRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/login' | '/lists' | '/todos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/login' | '/lists' | '/todos'
  id: '__root__' | '/' | '/_auth' | '/login' | '/_auth/lists' | '/_auth/todos'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/lists",
        "/_auth/todos"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/lists": {
      "filePath": "_auth.lists.tsx",
      "parent": "/_auth"
    },
    "/_auth/todos": {
      "filePath": "_auth.todos.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
